Fs2Part3Team3/2gi-docthru-3team-be

http/challenge.http
package-lock.json
package.json
prisma/mock.js
prisma/seed.js
src/app.js
src/controllers/challengeController.js
src/controllers/userController.js
src/middlewares/asyncHandler.js
src/repositories/challengeRepository.js
src/repositories/userRepository.js
src/routes/challengeRouter.js
src/services/challengeService.js
src/services/userService.js

- mock 데이터 모델에 안 맞는 부분 수정
- getChallenges 구현
- default 값은 page = 1, limit = 5 (변경 가능, 현재 페이지는 1부터 시작)
- field, type, process, keyword로 필터링 가능
- field, type, process 여러 값 받음
- data와 totalCount가 함께 감 (아래 예시)
```json
{
"data": [
{
"id": 1,
"title": "Next.js Workshop",
"field": "Next",
"docType": "Document",
"docUrl": "http://example.com/doc1",
"deadLine": "2024-12-01T23:59:59.000Z",
"description": "Next.js workshop for beginners.",
"progress": false,
"participants": 3,
"maxParticipants": 5
},
{
"id": 3,
"title": "API Mastery",
"field": "API",
"docType": "Document",
"docUrl": "http://example.com/doc3",
"deadLine": "2024-12-15T23:59:59.000Z",
"description": "API mastery challenge for developers.",
"progress": false,
"participants": 4,
"maxParticipants": 5
}
],
"totalCount": 2
}
```

Feat:#5-getChallenges

---

http/user.http
src/app.js
src/config/passport.js
src/controllers/userController.js
src/middlewares/passport/googleStrategy.js
src/middlewares/passport/jwtStrategy.js
src/middlewares/passport/localStrategy.js
src/routes/userRouter.js
src/services/userService.js

* 요청 예
```
POST http://localhost:3100/api/auth/refresh-token
Content-Type: application/json
Authorization: Bearer {accessToken}
{
"refreshToken": "{refreshToken}"
}
```
※ 중괄호는 변수표시일뿐 포함하지 않습니다.

refresh token 갱신

---

http/user.http
src/routes/userRouter.js

siginup 엔드포인트 변경

---

http/user.http
prisma/mock.js
src/config/passport.js
src/controllers/userController.js
src/middlewares/authMiddleware.js
src/routes/userRouter.js
src/services/userService.js

* access-token payload에 role 정보 추가
* authMiddleware.js 추가
* 사용예제는 userRouter.js 에 작성되어 있습니다.
* mockdata 에 비밀번호를 해싱된 비밀번호로 변경하였습니다.
* 변경된 비밀번호 : 12345678
* admin@example.com 계정 추가

관리자 권한 인가 미들웨어 구현

---

http/user.http
prisma/mock.js
prisma/seed.js
src/controllers/userController.js
src/middlewares/passport/jwtStrategy.js
src/services/userService.js
src/utils/logger.js

* 현재는 로그인할때 업데이트 기능을 추가하였습니다.
* 다른 활동(예: 챌린지 참여, 추천 등)이 수행되었을 때, 다음의 코드를 추가하시면 될 것 같습니다.
```
import { updateUserGrade } from '../services/userService.js';
// 작업 수행 함수 내에 
await updateUserGrade(user.id);
```
* 개발모드나 디버깅 모드일때, 간략하게 로그 출력 기능을 만들었습니다.
.env 에 다음 항목을 설정하시고, `devLog()`, `debugLog()`를 사용하시면 됩니다.
```
NODE_ENV=development
DEBUG=true
```

유저 grade 업데이트 기능

---

src/controllers/applicationController.js
src/repositories/applicationRepository.js
src/repositories/challengeRepository.js
src/routes/applicationRouter.js
src/services/applicationService.js
src/services/challengeService.js

- close #52
- 신규 챌린지 신청 목록 조회 정렬 오류 해결
- 신규 챌린지 신청 삭제 구현

신규 챌린지 신청 삭제 구현

---

prisma/migrations/20241121073037_add_content_column/migration.sql
prisma/mock.js
prisma/schema.prisma
src/controllers/applicationController.js
src/controllers/challengeController.js
src/repositories/applicationRepository.js
src/routes/applicationRouter.js
src/services/applicationService.js
src/services/challengeService.js

- close #56 
- 챌린지 신청 취소 Waiting 상태일 때만 취소 가능하도록 수정
- 신규 챌린지 신청 상세 조회 구현
```json
{
"id": 1,
"userId": 1,
"challengeId": 1,
"status": "Waiting",
"appliedAt": "2024-11-18T11:00:00.000Z",
"invalidationComment": null,
"invalidatedAt": null,
"challenge": {
"id": 1,
"title": "Next.js Workshop",
"field": "Next",
"docType": "Document",
"docUrl": "http://example.com/doc1",
"deadLine": "2024-12-01T23:59:59.000Z",
"description": "Next.js workshop for beginners.",
"progress": false,
"participants": 0,
"maxParticipants": 5
}
}
```

신규 챌린지 신청 상세 조회 구현

---

src/app.js
src/controllers/applicationController.js
src/controllers/feedbackController.js
src/repositories/applicationRepository.js
src/repositories/feedbackRepository.js
src/repositories/participationRepository.js
src/routes/feedbackRouter.js
src/routes/workRouter.js
src/services/applicationService.js
src/services/challengeService.js
src/services/feedbackService.js
src/services/participationService.js

- close #65 
- 에러 핸들러 적용
- 조회 시 hasMore 반환

피드백 조회, 생성, 수정, 삭제 구현

---

http/work.http
src/repositories/workRepository.js
src/services/workService.js

* challenge docUrl 추가하였습니다.
```
HTTP/1.1 200 OK
X-Powered-By: Express
Vary: Origin
Content-Type: application/json; charset=utf-8
Content-Length: 2550
ETag: W/"9f6-zvBZzeJghk1t4zSE8dOvjuH03F0"
Date: Mon, 25 Nov 2024 04:42:26 GMT
Connection: close
{
"id": 1,
"content": "일반적으로 개발자는 ...",
"lastModifiedAt": "2024-11-24T05:42:48.489Z",
"isSubmitted": true,
"submittedAt": "2024-11-18T13:00:00.000Z",
"user": {
"id": 1,
"nickname": "nick1"
},
"challenge": {
"id": 5,
"title": "Career Growth Tips",
"docUrl": "http://example.com/doc5"
},
"feedbacks": {
"list": [
{
"id": 1,
"content": "Great job!",
"createdAt": "2024-11-18T12:00:00.000Z",
"user": {
"nickname": "nick1"
}
},
{
"id": 2,
"content": "Needs improvement.",
"createdAt": "2024-11-18T12:10:00.000Z",
"user": {
"nickname": "nick3"
}
},
{
"id": 3, …
```

작업물 응답 수정(challenge docUrl)

---

src/repositories/challengeRepository.js
src/repositories/participationRepository.js
src/services/participationService.js

이미 참가한 챌린지인지 확인

---

http/work.http
prisma/mock.js
src/controllers/workController.js
src/services/workService.js

- close #{이슈 번호}
* 작업물 삭제 시 다음 기능 수행
1. 챌린지 참여기록 삭제 (Participate)
2. 챌린지 참여자 수 1 감소 (Challenge)
3. 작업물 삭제 로그 생성 (WorkLog)
4. 작업물 삭제 (Work)
* 삭제 성공 응답
```
HTTP/1.1 200 OK
{
"message": "작업물이 성공적으로 삭제되었으며, 챌린지 참여가 취소되었습니다."
}
```

작업물 삭제시 챌린지 포기 기능 추가

---

http/work.http
prisma/migrations/20241125073144_add_message_to_worklog/migration.sql
prisma/migrations/20241125080610_update_worlog2/migration.sql
prisma/schema.prisma
src/controllers/workController.js
src/services/workService.js

- close #{이슈 번호}
- 작업물 삭제시 관리자 메시지 추가
- message 는 관리자 삭제시 필수, 본인 삭제시는 옵션
- WorkLog 테이블의 message 필드에 저장됩니다.
```
DELETE http://localhost:3100/api/works/7
Content-Type: application/json
Authorization: Bearer {{accessToken}}
{
"message": "관리자가 삭제한 사유입니다."
}
```

작업물 삭제시 관리자 메시지 추가

---

http/myChallenge.http
http/user.http
http/work.http
src/app.js
src/controllers/myChallengeController.js
src/repositories/myChallengeRepository.js
src/routes/myChallengeRouter.js
src/services/myChallengeService.js
src/services/workService.js

- close #{이슈 번호}
- 참여 중인 챌린지 목록 조회
```
HTTP/1.1 200 OK
{
"list": [
{
"id": 9,
"title": "Node.js Fundamentals",
"field": "Web",
"docType": "Document",
"docUrl": "http://example.com/doc9",
"deadLine": "2024-12-22T23:59:59.000Z",
"description": "Learn the fundamentals of Node.js for backend development.",
"progress": true,
"participants": 2,
"maxParticipants": 5,
"myWork": {
"id": 25,
"userId": 1,
"challengeId": 9,
"content": "Work1",
"lastModifiedAt": "2024-11-25T08:37:04.264Z",
"isSubmitted": true,
"submittedAt": null
}
}
],
"totalCount": 1,
"hasMore": false
}
```
* 완료한 챌린지 목록 조회
```
응답 형식은'참여중인'과 동일
```
* 내가 신청한 챌린지 목록 조회
```
{
"list": [
{
"id": 7,
"userId": 1,
"challengeId": 7,
"status": "Accepted",
"appliedAt": "2024-11-18T11:40:00.000Z",
"invalidationComment": null,
"invalidatedAt": …
```

마이챌린지 API 구현(참여중, 완료한, 신청한)

---

src/controllers/challengeController.js

- close #77 
- controller user 삭제

Fix: user 삭제

---

src/services/applicationService.js
src/services/participationService.js

- close #81 
-  승인 시 progress: true로 변경

챌린지 승인 오류 수정

---

src/config/passport.js
src/controllers/applicationController.js
src/controllers/userController.js
src/middlewares/passport/googleStrategy.js
src/repositories/challengeRepository.js
src/routes/applicationRouter.js
src/routes/userRouter.js
src/services/applicationService.js

- close #85 
- keyword를 challenge의 title과 비교해야하는데 바로 title과 비교해서 에러남
- 본인이 신청한 챌린지는 수정할 수 있도록 챌린지 목록에서 applications 받을 수 있도록 수정
- 본인이 신청한 챌린지의 승인 현황에 접근할 수 있도록 수정

resolve keyword error

---

src/services/myChallengeService.js

- close #87 
- applications의 status가 Accepted 상태인 데이터만 받도록 filter 기능 추가

getCompletedChallenge 수정 완료

---

src/repositories/workRepository.js
src/services/workService.js

workdetail 반환값 수정

---

http/work.http
prisma/migrations/20241128071836_add_feedback_log/migration.sql
prisma/migrations/20241128071901_feedback_log_trigger/migration.sql
prisma/migrations/20241128122057_noname/migration.sql
prisma/schema.prisma
prisma/seed.js
src/controllers/feedbackController.js
src/middlewares/asyncHandler.js
src/repositories/feedbackRepository.js
src/repositories/workLogRepository.js
src/services/feedbackService.js

- close #{이슈 번호}
- FeedbackLog 테이블 추가
- 피드백 로그 관련 마이그레이션 생성(Trigger & Strored Procedure 작성)
- 피드백 수정/삭제 수정

피드백 로그 기능 구현 (by Trigger & Strored Procedure)

---

src/repositories/feedbackRepository.js

feedback list에 nickname 추가
